services:
  - type: web
    name: discountmart
    env: node
    buildCommand: |
      npm install --workspaces --include-workspace-root
      npm run build --workspace=client
      npm run build --workspace=server
    startCommand: node server/build/index.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        sync: false
     - key: FRONTEND_URL
        value: https://discountmart.onrender.com
    buildFilter:
      paths:
        - client/**
        - server/**
    autoDeploy: true
    branch: main
    rootDir: .
